"use client"

/**
 * Generate a PPTX file from slides data using pptxgenjs.
 * This runs entirely in the browser.
 */

type Slide = {
  title: string
  bullets: string[]
  speakerNotes?: string
}

const THEME = {
  // Slide dimensions (LAYOUT_WIDE = 13.33 x 7.5 in)
  W: 13.33,
  H: 7.5,
  // Colors
  titleBg: "1E293B",       // slate-800
  titleText: "F8FAFC",     // slate-50
  accentColor: "3B82F6",   // blue-500
  bodyText: "1E293B",      // slate-800
  bodyBg: "FFFFFF",
  bulletText: "334155",    // slate-700
  notesText: "64748B",     // slate-500
  slideNumText: "94A3B8",  // slate-400
}

export async function generatePptx(presentationTitle: string, slides: Slide[]): Promise<void> {
  // Dynamic import so this only loads in browser when needed
  const PptxGenJS = (await import("pptxgenjs")).default
  const pptx = new PptxGenJS()

  pptx.layout = "LAYOUT_WIDE"
  pptx.title = presentationTitle
  pptx.subject = "Generated by Paper Explainer"

  // ── Cover slide ─────────────────────────────────────────────────────────────
  const cover = pptx.addSlide()
  cover.background = { color: THEME.titleBg }

  // Decorative accent bar
  cover.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: THEME.H - 0.08,
    w: THEME.W,
    h: 0.08,
    fill: { color: THEME.accentColor },
    line: { color: THEME.accentColor },
  })

  // Title text
  cover.addText(presentationTitle, {
    x: 0.8,
    y: 1.8,
    w: THEME.W - 1.6,
    h: 2.4,
    fontSize: 36,
    bold: true,
    color: THEME.titleText,
    align: "center",
    valign: "middle",
    wrap: true,
  })

  // Sub-label
  cover.addText("Generated by Paper Explainer", {
    x: 0.8,
    y: 4.4,
    w: THEME.W - 1.6,
    h: 0.5,
    fontSize: 14,
    color: "94A3B8",
    align: "center",
    italic: true,
  })

  // Slide count badge
  cover.addText(`${slides.length} slide${slides.length !== 1 ? "s" : ""}`, {
    x: 0.8,
    y: 5.1,
    w: THEME.W - 1.6,
    h: 0.4,
    fontSize: 12,
    color: "475569",
    align: "center",
  })

  // ── Content slides ───────────────────────────────────────────────────────────
  slides.forEach((slide, idx) => {
    const s = pptx.addSlide()
    s.background = { color: THEME.bodyBg }

    // Top title bar
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: THEME.W,
      h: 1.3,
      fill: { color: THEME.titleBg },
      line: { color: THEME.titleBg },
    })

    // Accent stripe at bottom of title bar
    s.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 1.3,
      w: THEME.W,
      h: 0.05,
      fill: { color: THEME.accentColor },
      line: { color: THEME.accentColor },
    })

    // Slide title
    s.addText(slide.title, {
      x: 0.5,
      y: 0.1,
      w: THEME.W - 2.0,
      h: 1.1,
      fontSize: 24,
      bold: true,
      color: THEME.titleText,
      valign: "middle",
      wrap: true,
    })

    // Slide number
    s.addText(`${idx + 1} / ${slides.length}`, {
      x: THEME.W - 1.5,
      y: 0.1,
      w: 1.3,
      h: 1.1,
      fontSize: 11,
      color: THEME.slideNumText,
      align: "right",
      valign: "middle",
    })

    // Bullet points
    const hasNotes = !!slide.speakerNotes
    const bulletAreaH = hasNotes ? 4.5 : 5.5

    if (slide.bullets.length > 0) {
      const bulletObjs = slide.bullets.map((b, bIdx) => [
        {
          text: `•  ${b}`,
          options: {
            fontSize: 18,
            color: THEME.bulletText,
            breakLine: bIdx < slide.bullets.length - 1,
            paraSpaceBefore: bIdx === 0 ? 0 : 8,
          },
        },
      ]).flat()

      s.addText(bulletObjs, {
        x: 0.5,
        y: 1.55,
        w: THEME.W - 1.0,
        h: bulletAreaH,
        valign: "top",
        wrap: true,
      })
    }

    // Speaker notes (shown as faded footer)
    if (slide.speakerNotes) {
      s.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: THEME.H - 1.05,
        w: THEME.W,
        h: 1.05,
        fill: { color: "F1F5F9" },
        line: { color: "E2E8F0" },
      })
      s.addText(`🗒  ${slide.speakerNotes}`, {
        x: 0.5,
        y: THEME.H - 1.0,
        w: THEME.W - 1.0,
        h: 0.95,
        fontSize: 11,
        color: THEME.notesText,
        italic: true,
        valign: "middle",
        wrap: true,
      })

      // Also add to actual speaker notes panel
      s.addNotes(slide.speakerNotes)
    }
  })

  // ── Thank-you slide ──────────────────────────────────────────────────────────
  const outro = pptx.addSlide()
  outro.background = { color: THEME.titleBg }

  outro.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: THEME.H - 0.08,
    w: THEME.W,
    h: 0.08,
    fill: { color: THEME.accentColor },
    line: { color: THEME.accentColor },
  })

  outro.addText("Thank You", {
    x: 0.8,
    y: 2.5,
    w: THEME.W - 1.6,
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: THEME.titleText,
    align: "center",
    valign: "middle",
  })

  outro.addText("Generated by Paper Explainer", {
    x: 0.8,
    y: 4.2,
    w: THEME.W - 1.6,
    h: 0.5,
    fontSize: 14,
    color: "64748B",
    align: "center",
    italic: true,
  })

  const safeFileName = presentationTitle.replace(/[^a-zA-Z0-9\s-]/g, "").substring(0, 60).trim() || "slides"
  await pptx.writeFile({ fileName: `${safeFileName}.pptx` })
}
